In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IPL.csv')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6776\418616701.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('IPL.csv')

In [3]:
df.shape

(283678, 65)

In [4]:
df.columns.tolist()

['Unnamed: 0',
 'match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'power_surge_start',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'next_batter',
 'striker_out']

In [5]:
df['match_won_by'].value_counts(dropna=False).head(20)

match_won_by
Mumbai Indians                 36432
Chennai Super Kings            34878
Kolkata Knight Riders          31729
Rajasthan Royals               28295
Royal Challengers Bangalore    26801
Sunrisers Hyderabad            22665
Kings XI Punjab                20162
Delhi Daredevils               15709
Delhi Capitals                 12762
Gujarat Titans                  9491
Punjab Kings                    9142
Lucknow Super Giants            7925
Deccan Chargers                 7013
Royal Challengers Bengaluru     5194
Unknown                         4724
Gujarat Lions                   3063
Pune Warriors                   2883
Rising Pune Supergiant          2383
Kochi Tuskers Kerala            1322
Rising Pune Supergiants         1105
Name: count, dtype: int64

In [6]:
df.groupby('match_id')['match_won_by'].nunique().value_counts()

match_won_by
1    1193
Name: count, dtype: int64

In [7]:
df[['batting_team','bowling_team','toss_winner','toss_decision','venue']].head()

,batting_team,bowling_team,toss_winner,toss_decision,venue
0,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,M Chinnaswamy Stadium
1,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,M Chinnaswamy Stadium
2,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,M Chinnaswamy Stadium
3,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,M Chinnaswamy Stadium
4,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,M Chinnaswamy Stadium

In [8]:
df.isnull().sum().sort_values(ascending=False).head(15)

power_surge_start    283678
team_reviewed        282771
review_batter        282771
review_decision      282771
umpire               282771
method               279788
superover_winner     279782
result_type          278954
fielders             273433
next_batter          270085
new_batter           270085
player_out           269572
wicket_kind          269572
extra_type           268185
runs_target          147168
dtype: int64

In [9]:
df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [10]:
df['match_won_by'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Daredevils',
       'Royal Challengers Bangalore', 'Rajasthan Royals',
       'Kings XI Punjab', 'Deccan Chargers', 'Mumbai Indians', 'Unknown',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [11]:
df[['year','month','day']].drop_duplicates().head()

      year  month  day
0     2008      4   18
225   2008      4   19
692   2008      4   20
1178  2008      4   21
1419  2008      4   22

In [12]:
import pandas as pd

In [13]:
match_df = df.groupby('match_id').agg({
    'batting_team': 'first',
    'bowling_team': 'first',
    'venue': 'first',
    'city': 'first',
    'toss_winner': 'first',
    'toss_decision': 'first',
    'year': 'first',
    'month': 'first',
    'day': 'first',
    'match_won_by': 'first'
}).reset_index()

In [14]:
TEAM_MAP = {
    "mumbai indians": "mi",
    "chennai super kings": "csk",
    "royal challengers bangalore": "rcb",
    "royal challengers bengaluru": "rcb",
    "sunrisers hyderabad": "srh",
    "kolkata knight riders": "kkr",
    "delhi capitals": "dc",
    "delhi daredevils": "dc",
    "rajasthan royals": "rr",
    "punjab kings": "pbks",
    "kings xi punjab": "pbks",
    "lucknow super giants": "lsg",
    "gujarat titans": "gt",
    "rising pune supergiant": "rps",
    "rising pune supergiants": "rps",
    "gujarat lions": "gl",
    "kochi tuskers kerala": "ktk",
    "deccan chargers": "dch",
    "pune warriors": "pwi",
}

HOME_VENUES = {
    "mi":   ["wankhede stadium", "brabourne stadium"],
    "csk":  ["ma chidambaram stadium", "chepauk"],
    "rcb":  ["m chinnaswamy stadium", "chinnaswamy"],
    "srh":  ["rajiv gandhi international stadium", "uppal"],
    "kkr":  ["eden gardens"],
    "dc":   ["arun jaitley stadium", "feroz shah kotla"],
    "rr":   ["sawai mansingh stadium", "sms stadium"],
    "pbks": ["punjab cricket association stadium", "is bindra stadium", "mohali"],
    "lsg":  ["ekana cricket stadium", "ekana"],
    "gt":   ["narendra modi stadium", "motera"],
}

In [15]:
def map_team(team):
    if pd.isna(team):
        return "unknown"
    return TEAM_MAP.get(str(team).lower().strip(), str(team).lower().strip())

def is_home(team, venue):
    team = map_team(team)
    venue = str(venue).lower().strip()
    home_list = HOME_VENUES.get(team, [])
    return int(any(h in venue for h in home_list))

In [16]:
for col in ['batting_team','bowling_team','toss_winner','match_won_by']:
    match_df[col] = match_df[col].apply(map_team)

In [17]:
match_df = match_df[match_df['match_won_by'] != 'unknown']

In [18]:
team_counts = match_df['match_won_by'].value_counts()
valid_teams = team_counts[team_counts > 30].index
match_df = match_df[match_df['match_won_by'].isin(valid_teams)]

In [19]:
match_df = match_df.sort_values(by=['year','month','day'])

In [20]:
team_stats = {}

bat_strength = []
bowl_strength = []

In [21]:
for _, row in match_df.iterrows():
    bt = row['batting_team']
    bw = row['bowling_team']
    winner = row['match_won_by']
    
    for t in [bt, bw]:
        if t not in team_stats:
            team_stats[t] = {'matches': 0, 'wins': 0}
    
    bt_wr = team_stats[bt]['wins'] / team_stats[bt]['matches'] if team_stats[bt]['matches'] > 0 else 0.5
    bw_wr = team_stats[bw]['wins'] / team_stats[bw]['matches'] if team_stats[bw]['matches'] > 0 else 0.5
    
    bat_strength.append(bt_wr)
    bowl_strength.append(bw_wr)
    
    team_stats[bt]['matches'] += 1
    team_stats[bw]['matches'] += 1
    team_stats[winner]['wins'] += 1

match_df['batting_strength'] = bat_strength
match_df['bowling_strength'] = bowl_strength

In [22]:
match_df['batting_home'] = match_df.apply(
    lambda x: is_home(x['batting_team'], x['venue']), axis=1)

match_df['bowling_home'] = match_df.apply(
    lambda x: is_home(x['bowling_team'], x['venue']), axis=1)

In [23]:
X = match_df.drop(columns=['match_id','match_won_by'])
y = match_df['match_won_by']

In [24]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [25]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [26]:
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['int64','float64']).columns.tolist()

In [27]:
from sklearn.compose import ColumnTransformer

In [28]:
preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
    ('num', 'passthrough', numerical_cols)
])

# MODELS

In [29]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [30]:
rf = RandomForestClassifier(n_estimators=200, random_state=42)

In [31]:
xgb = XGBClassifier(eval_metric='mlogloss', use_label_encoder=False)

In [32]:
lgbm = LGBMClassifier()

In [33]:
ensemble = VotingClassifier(
    estimators=[('rf', rf), ('xgb', xgb), ('lgbm', lgbm)],
    voting='soft'
)

In [34]:
from sklearn.pipeline import Pipeline

In [35]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', ensemble)
])

In [37]:
from sklearn.model_selection import TimeSeriesSplit
import numpy as np

In [38]:
tscv = TimeSeriesSplit(n_splits=5)

y_pred = np.zeros(len(y_encoded))

for train_idx, test_idx in tscv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train = y_encoded[train_idx]

    pipeline.fit(X_train, y_train)
    y_pred[test_idx] = pipeline.predict(X_test)

y_pred = y_pred.astype(int)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [39]:
valid_idx = y_pred != 0

In [40]:
from sklearn.metrics import accuracy_score, classification_report

In [41]:
print("Accuracy:", accuracy_score(y_encoded[valid_idx], y_pred[valid_idx]))
print("\nClassification Report:\n")
print(classification_report(y_encoded[valid_idx], y_pred[valid_idx], target_names=le.classes_))

Accuracy: 0.5143979057591623

Classification Report:

              precision    recall  f1-score   support

         csk       0.00      0.00      0.00        39
          dc       0.47      0.54      0.50        87
          gt       0.69      0.34      0.46        32
         kkr       0.54      0.48      0.51       104
         lsg       0.33      0.10      0.16        29
          mi       0.57      0.78      0.66       112
        pbks       0.48      0.61      0.54        89
         rcb       0.56      0.58      0.57       103
          rr       0.48      0.53      0.50        80
         srh       0.45      0.44      0.45        89

    accuracy                           0.51       764
   macro avg       0.46      0.44      0.43       764
weighted avg       0.49      0.51      0.49       764

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [42]:
rf = RandomForestClassifier(
    n_estimators=300,
    class_weight='balanced',
    random_state=42
)

In [44]:
xgb = XGBClassifier(
    eval_metric='mlogloss',
    scale_pos_weight=1,
    random_state=42
)

In [45]:
lgbm = LGBMClassifier(
    class_weight='balanced',
    random_state=42
)

In [46]:
recent_form = {}

bat_recent = []
bowl_recent = []

for _, row in match_df.iterrows():
    bt = row['batting_team']
    bw = row['bowling_team']
    winner = row['match_won_by']
    
    for t in [bt, bw]:
        if t not in recent_form:
            recent_form[t] = []
    
    bt_form = np.mean(recent_form[bt][-5:]) if len(recent_form[bt]) >= 1 else 0.5
    bw_form = np.mean(recent_form[bw][-5:]) if len(recent_form[bw]) >= 1 else 0.5
    
    bat_recent.append(bt_form)
    bowl_recent.append(bw_form)
    
    recent_form[bt].append(1 if winner == bt else 0)
    recent_form[bw].append(1 if winner == bw else 0)

match_df['batting_recent_form'] = bat_recent
match_df['bowling_recent_form'] = bowl_recent

In [47]:
match_df['toss_advantage'] = (
    match_df['toss_winner'] == match_df['batting_team']
).astype(int)

In [49]:
match_df = match_df.drop(['city'], axis=1)

In [50]:
pipeline.fit(X, y_encoded)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team', 'venue',
                                                   'city', 'toss_winner',
                                                   'toss_decision']),
                                                 ('num', 'passthrough',
                                                  ['year', 'month', 'day',
                                                   'batting_strength',
                                                   'bowling_strength',
                                                   'batting_home',
                                                   'bowling_home'])])),
                ('model',
                 VotingClassifier(estimators=[('rf',
                                               Ra...
                                                             importance_type=None,
                                                             interaction_constraints=None,
                                                             learning_rate=None,
                                                             max_bin=None,
                                                             max_cat_threshold=None,
                                                             max_cat_to_onehot=None,
                                                             max_delta_step=None,
                                                             max_depth=None,
                                                             max_leaves=None,
                                                             min_child_weight=None,
                                                             missing=nan,
                                                             monotone_constraints=None,
                                                             multi_strategy=None,
                                                             n_estimators=None,
                                                             n_jobs=None,
                                                             num_parallel_tree=None, ...)),
                                              ('lgbm', LGBMClassifier())],
                                  voting='soft'))])

In [51]:
import joblib

joblib.dump(pipeline, "ipl_model_v1.pkl")
joblib.dump(le, "label_encoder_v1.pkl")

['label_encoder_v1.pkl']

In [52]:
print("Accuracy:", accuracy_score(y_encoded[valid_idx], y_pred[valid_idx]))
print("\nClassification Report:\n")
print(classification_report(y_encoded[valid_idx], y_pred[valid_idx], target_names=le.classes_))

Accuracy: 0.5143979057591623

Classification Report:

              precision    recall  f1-score   support

         csk       0.00      0.00      0.00        39
          dc       0.47      0.54      0.50        87
          gt       0.69      0.34      0.46        32
         kkr       0.54      0.48      0.51       104
         lsg       0.33      0.10      0.16        29
          mi       0.57      0.78      0.66       112
        pbks       0.48      0.61      0.54        89
         rcb       0.56      0.58      0.57       103
          rr       0.48      0.53      0.50        80
         srh       0.45      0.44      0.45        89

    accuracy                           0.51       764
   macro avg       0.46      0.44      0.43       764
weighted avg       0.49      0.51      0.49       764

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])